version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:${MYSQL_CONTAINER_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - compilador-network
    depends_on:
      - mysql

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    image: front-end
    container_name: front-end
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - compilador-network
    depends_on:
      - backend

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_CONTAINER_PORT}"
    networks:
      - compilador-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  compilador-network:

volumes:
  mysql-data: